RUMINATE_TEST_SOURCES := ruminate.c
RUMINATE_TEST_SOURCES := $(RUMINATE_TEST_SOURCES:%=$(CURDIR)/%)

RUMINATE_TEST_OBJECTS := $(RUMINATE_TEST_SOURCES:.c=.o)
RUMINATE_TEST_DEPS := $(RUMINATE_TEST_SOURCES:.c=.d)

TEST_SOURCES := main.c
TEST_SOURCES := $(TEST_SOURCES:%=$(CURDIR)/%)

TEST_OBJECTS := $(TEST_SOURCES:.c=.o)
TEST_DEPS := $(TEST_SOURCES:.c=.d)
