$(COMPILE_FLAGS_PREFIX)FLAGS_PREPROC_AND_COMPILER_C := $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROC_AND_COMPILER) $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROC_AND_COMPILER_C)
$(COMPILE_FLAGS_PREFIX)FLAGS_PREPROC_AND_COMPILER_CXX := $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROC_AND_COMPILER) $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROC_AND_COMPILER_CXX)

$(COMPILE_FLAGS_PREFIX)FLAGS_PREPROCESSOR := $($(COMPILE_FLAGS_PREFIX)FLAGS_ALL) $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROCESSOR) $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROC_AND_COMPILER)
$(COMPILE_FLAGS_PREFIX)FLAGS_PREPROCESSOR_C := $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROCESSOR) $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROCESSOR_C)
$(COMPILE_FLAGS_PREFIX)FLAGS_PREPROCESSOR_CXX := $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROCESSOR) $($(COMPILE_FLAGS_PREFIX)FLAGS_PREPROCESSOR_CXX)

$(COMPILE_FLAGS_PREFIX)FLAGS_COMPILER := $($(COMPILE_FLAGS_PREFIX)FLAGS_ALL) $($(COMPILE_FLAGS_PREFIX)FLAGS_COMPILER)
$(COMPILE_FLAGS_PREFIX)FLAGS_COMPILER_C := $($(COMPILE_FLAGS_PREFIX)FLAGS_COMPILER) $($(COMPILE_FLAGS_PREFIX)FLAGS_COMPILER_C)
$(COMPILE_FLAGS_PREFIX)FLAGS_COMPILER_CXX := $($(COMPILE_FLAGS_PREFIX)FLAGS_COMPILER) $($(COMPILE_FLAGS_PREFIX)FLAGS_COMPILER_CXX)

$(COMPILE_FLAGS_PREFIX)FLAGS_LINKER := $($(COMPILE_FLAGS_PREFIX)FLAGS_ALL) $($(COMPILE_FLAGS_PREFIX)FLAGS_LINKER)
